### ISSUE TITLE
Volume still shown even when replay stopped, and a question

### ISSUE THREAD

**Issue by 111MilesToGo** [cboxdoerfer/ddb_vu_meter#3]
Thanks for your DeaDBeeF plugins! I use VU meter, musical spectrum, waveform seekbar and spectrogram.

Regarding VU meter:
(1) It does display volume even when no replay is going on.
(2) The volume shown in quiet portions of a track (e.g. the first 3-4 seconds of a classical recording which are almost dead silence) seems to be too large.
(3) I have VU and musical spectrum side by side, same dB scale. However, I can't really match by eye what I see - the VU meter always seems to be much higher. But maybe this is due to how the volume units are defined in these plugins. In foobar2000, the eye does match what the corresponding displays do show. Maybe it's a mistake to expect them to be at similar heights - I would be grateful for pointing to the proper volume definitions.

Thanks!

DeaDBeeF 0.7.2 and plugins downloaded and installed a few days ago
Linux Mint 18.2 and openSUSE Tumbleweed

**Comment by cboxdoerfer** [comment]
> (1) It does display volume even when no replay is going on.

With "no replay is going on" do you mean the player is paused or stopped? If yes, which one of the two?
 Or do you mean silent parts within a track?

> (2) The volume shown in quiet portions of a track (e.g. the first 3-4 seconds of a classical recording which are almost dead silence) seems to be too large.
(3) I have VU and musical spectrum side by side, same dB scale. However, I can't really match by eye what I see - the VU meter always seems to be much higher. But maybe this is due to how the volume units are defined in these plugins. In foobar2000, the eye does match what the corresponding displays do show. Maybe it's a mistake to expect them to be at similar heights - I would be grateful for pointing to the proper volume definitions.

I'll look into that. I actually just implemented the algorithm for the VU meter from the top of my head, , without looking up how others do it or how it's supposed to be. So there's a chance I'm just using the wrong algorithm.

**Comment by 111MilesToGo** [comment]
Regarding (1): When the DeaDBeeF app is launched, there's no replay, of course, and the VU meter is blank. Then start to replay a track. Pausing it leaves the VU meter up - fine. Stopping the replay leaves the VU meter up, too - I feel it should drop out then.

Regarding (2): Silent parts within a track have the VU meter at some volume which seems too high to me. This might actually be the same issue as (3).

**Comment by cboxdoerfer** [comment]
@111MilesToGo , I think I fixed both issues. Please let me know if it works for you.

**Comment by 111MilesToGo** [comment]
Wow, thanks. Sorry to be late, I was updating my Windows virtual machine...

Well, since I am new to github, **how do I get the new VU Meter?** I did download the zip file from the "Get plugins" on the DeaDBeeF website, but that seems to be the old one. AT least its behaviour doesn't look different.

**Comment by 111MilesToGo** [comment]
Sorry to intrude again, I am just too inexperienced to build the new VU version from source. Please, could you make the binaries/zip public on the DeaDBeeF "Get Plugin" website? Thanks a lot for your help and time.

**Comment by 111MilesToGo** [comment]
So sorry to intrude, don't know enough about github. Are you receiving the comments even when the issue is closed? I posted that I should really like you to publish the new VU meter (zip on DDB website), since I can't build from source.

Thanks a lot, and sorry again for reaching out to you.

Cheers!

Am 21.09.2017 um 12:28 schrieb Christian Boxdörfer <notifications@github.com<mailto:notifications@github.com>>:


@111MilesToGo<https://github.com/111milestogo> , I think I fixed both issues. Please let me know if it works for you.

**Comment by cboxdoerfer** [comment]
Hi, I do receive those comments, but I'm busy until the weekend. Tomorrow I'm back at my computer and can help you.

**Comment by 111MilesToGo** [comment]
Lieber Herr Boxdörfer,

Danke für Ihre Hilfe. Leider habe ich ab jetzt für 1,5 Wochen keinen Computer, kann erst danach testen. Aber ich denke, alles funktioniert...

Sie müssen mich für "nervig" halten - dann tiefe Entschuldigung. Hatte nur kurzfristig wohl zuviel Neues versucht, github, compile/make und insbesondere Devel-Libs, zwei DDBF Plugins (Ihre und ein SoX Resampler von silentlexx).

Nochmals Danke und 'Tschuldigung, bis inn1,5 Wochen!

Besten Gruß und schönes Wochenende!

111MilesToGo


Am 22.09.2017 um 15:45 schrieb Christian Boxdörfer <notifications@github.com<mailto:notifications@github.com>>:


Hi, I do receive those comments, but I'm busy until the weekend. Tomorrow I'm back at my computer and can help you.

**Comment by 111MilesToGo** [comment]
Thank you for the updated VU Meter. I could test it now. Everything looks reasonable now (levels as compared to Musical Spectrum) and functions fine (pause leaves VU and MusSpec up where they were, stop makes them disappear).

Cheers,
111MilesToGo
